### PR TITLE
[IMPROVEMENT](#841, #277) Extract libs to bower components

### PR DESCRIPTION
**Pull request by hyukmin-kwon**
[DESC.] We extracted 4 external modules from 11 external modules in app/ide/src/lib to bower components.
And we also extracted  3 external modules from 10 external modules in code-editor related plugins to bower components.

[Review on Reviewable](https://reviewable.io/reviews/webida/webida-client/892)

### CODE REVIEW

**Comment by kyungmi** [comment]
Merged build finished. Test FAILed.

**Comment by hyukmin-kwon** [comment]
Previous comment is an automatic message.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/892#-:-KAYPI7h6N3OUu0X6U4F:-1509437730)*

**Comment by hwshim** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/892)*

**Comment by gotchazipc** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/892)*

**Comment by gotchazipc** [comment]
due to DNS problem, jenkins code convention checking was broken and cannot execute again. It seems that this PR may have no effect on coding convention

**Pull request merged**
