### PR TITLE
[DOCUMENT](#773) JSDoc for source in git plugin

### PR DESCRIPTION
**Pull request by minsung-jin**
- separates the author

Signed-off-by: Minsung Jin <minsung.jin@samsung.com>

[Review on Reviewable](https://reviewable.io/reviews/webida/webida-client/878)

### CODE REVIEW

**Comment by minsung-jin** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/878)*

**Comment by hwshim** [comment]
Reviewed 7 of 7 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/878)*

**Comment by gotchazipc** [comment]
Reviewed 7 of 7 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/878)*

**Comment by hwshim** [comment]
This is test

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/878#-:-K8O1jTP3wbWpZarAVWx:-1393408021)*

**Comment by gotchazipc** [comment]
review comment on git-command-diff.js - looks good? 

---

Reviewed 2 of 7 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/878#-:-K8O1i8B6vivutpioUew:-1053337691)*

**Comment by gseok** [comment]
nice~ 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/878#-:-K8OU1KhrwdJkXcdO_-e:-1392066364)*

**Pull request merged**
