### PR TITLE
[IMPROVEMENT] support recursive bower install in running grunt

### LINKED ISSUE #880: Build system need to handle bower task recursively
This issue comes from #841 and #277 

Since we're moving dependencies to bower, 
1) Some plugins like code editor needs their own bower install tasks while building. 
2) Top level bower.json should have only 'common' dependencies for all plugins. 

So, Gruntfile should be changed to run bower install for every plugin directory when the plugin has bower.json file. Use grunt-auto-install instead of grunt-bower. Keep 'same' excluding patterns of current grunt-bower tasks for now. (When package system comes, resolving package-specific external dependencies should be handled by the build system of the package itself)

### PR DESCRIPTION
**Pull request by gotchazipc**
resolves #880  

- replaced grunt-bower to grunt-auto-install
- added excluding project wizard templates

[Review on Reviewable](https://reviewable.io/reviews/webida/webida-client/881)

### CODE REVIEW

**Comment by hwshim** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/881)*

**Comment by minsung-jin** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/881)*

**Comment by gseok** [comment]
*[Gruntfile.js, line 206 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/881#-K8TESCsHbJ6HrBbttn0:-K8TESCtbq6HTH21EiHQ:1630991328) ([raw file](https://github.com/webida/webida-client/blob/f3ab1547767740c52f08233505229ab4290decbb/Gruntfile.js#L206)):*
Actually, the 'auto-install' is used to 'bower'.
so.. how about grunt job name for 'auto_install_with_bower'
It  just opinion...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/881)*

**Comment by gseok** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/881)*

**Comment by gotchazipc** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Gruntfile.js, line 206 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/881#-K8TESCsHbJ6HrBbttn0:-K8XK10AnhMcVuHDiAUe:-711115053) ([raw file](https://github.com/webida/webida-client/blob/f3ab1547767740c52f08233505229ab4290decbb/Gruntfile.js#L206)):*
I've tested but grunt cannot wire grunt-auto-install task to other name than 'auto_install'. It's hard-coded in the grunt-auto-install package, and changing it will be another burden to maintain. (Expanding the plugin to support arbitrary commands would be pretty funny, but not for now. Next big thing (1.7) will hange everything.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/881)*

**Comment by gseok** [comment]
It makes sense~!!. 
Thank you for your comment... I learned about the 'grunt' tool's detail functionally~~!!!

**Pull request merged**
