### PR TITLE
[ENHANCEMENT] #327 Quit does not work when a user access IDE directly

### PR DESCRIPTION
**Pull request by minsung-jin**
Alert to miss a window.opener

Signed-off-by: Minsung Jin <minsung.jin@samsung.com>

### CODE REVIEW

**Comment by happibum** [comment]
Showing console error message via alert window is not helpful to casual users.
How about the following message?

Quit does not work when IDE was opened by a direct URL.
Please close the browser tab to quit the IDE.

**Comment by cimfalab** [comment]
I agree with @happibum .

**Comment by happibum** [comment]
Oh, my comment has gone. For the record, I put it again here.

Showing the console error message via alert window is not helpful to casual users.
How about the following message?

Quit does not work when IDE was opened by a direct URL.
Please close the browser tab to quit the IDE.

**Comment by minsung-jin** [comment]
I did not do anything for your comment.
Your opinion has been changed to reflect the message.

**Comment by happibum** [comment]
Whatever. :)
I did not change my opinion and the commit has been changed to reflect my comment.

**Pull request merged**
