### PR TITLE
[TASK] return of func will be saved to return of forEachKey with same…

### PR DESCRIPTION
**Pull request by minsung-jin**
return of function will be saved to return of forEachKey with same key

Signed-off-by: Minsung Jin <minsung.jin@samsung.com>

### CODE REVIEW

**Comment by wcho** [comment]
why don't you use _.forIn() and _.forOwn()?

**Comment by minsung-jin** [comment]
Loadash is possible, but this is an utility function.

**Comment by wcho** [comment]
Lodash is used widely in this project. I think it's not a good idea to reinvent the wheel.

**Comment by hwshim** [comment]
Let's consider this again later when this utility is really needed.
Thanks.

**Pull request closed without merging**
