### PR TITLE
[BUGFIX] Now editor(s) successfully recovered on starting ide

### PR DESCRIPTION
**Pull request by hwshim**

### CODE REVIEW

**Comment by wcho** [comment]
This issue looks like the editor plugin which depends on preference plugin is opened by editor/open topic.
I think the editor should have preference in its requirement not introducing another dependency management system.

**Comment by hwshim** [comment]
@wcho : I'll consider your opinion. Thanks.

**Comment by hwshim** [comment]
@wcho 
I tried add the following to the plugins/editors/plugin.json
```json
"requirement": "webida.common.workbench & webida.preference", 
```
But the console spit out the followings
```
TypeError: Cannot read property 'webida.editor.text-editor:editorconfig' of undefined
    at Object.getValue (https://~~~/common/src/webida/plugins/workbench/preference-system/store.js:165:35)
```
Basically, I think your idea is desirable.
If a plugin B depends on a plugin A, B should be loaded after A complete it's preparation.
But in this case there are some problems.

1) the workbench plugin (which editors plugin describes as a requirement already) loads store.js
2) store loaded asynchronously
3) editor parts needs store's data(preference) during editor recovering process.

A plugin "webida.preference" introduced by @kyungmi  recently, but I had no time to inspect it.
So I'll check and discuss about it with @kyungmi  then handle this problem as a desirable way.
We will avoid using promiseMap if it is not desirable (and if there is a better way).
(But promiseMap keeps solving this temporally until we find the better way.)
We are always welcome great idea.
Thanks.

**Comment by kyungmi** [comment]
@hwshim The `TypeError` issue you mentioned above was not related with the preference directly. The reason was `TextEditor` had used "old" preference store. And I resolved the issue with PR#468. You cannot use `..preference-system/store.js` no more.

There are some plugins that need to load files (meta or configuration) asynchronously. So I think the issues can be globally turned up our workbench. It seems to be needed the way to handle with these cases.

**Pull request merged**
