### PR TITLE
[DOCUMENT](#771) JSDoc for sources in code-editor plugin

### PR DESCRIPTION
**Pull request by hyukmin-kwon**
[DESC.]
 JSDoc for sources in code-editor plugin.

[Review on Reviewable](https://reviewable.io/reviews/webida/webida-client/883)

### CODE REVIEW

**Comment by gseok** [comment]
*[apps/ide/src/plugins/webida.editor.code-editor/preferences/preference-contentassist.js, line 39 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aq8oWi6xsccBLL1nX:-K8aq8oWi6xsccBLL1nY:1298122023) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/preferences/preference-contentassist.js#L39)):*
please remove unused space...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by gseok** [comment]
*[apps/ide/src/plugins/webida.editor.code-editor/preferences/preference-contentassist.js, line 51 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqHhBdJPsJyH3fWn9:-K8aqHhBdJPsJyH3fWnA:-2144628761) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/preferences/preference-contentassist.js#L51)):*
please remove unused space

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by gseok** [comment]
*[apps/ide/src/plugins/webida.editor.code-editor/preferences/preference-main.js, line 36 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqM9DLLj8UcRhKFtb:-K8aqM9DLLj8UcRhKFtc:-795354786) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/preferences/preference-main.js#L36)):*
please, remove unused space character

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by gseok** [comment]
*[apps/ide/src/plugins/webida.editor.code-editor/snippet.js, line 322 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqfeRZH2sb6EemTQq:-K8aqfeSK4OrA2wH-XtA:-795354786) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/snippet.js#L322)):*
please, remove unused space character

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by gseok** [comment]
*[apps/ide/src/plugins/webida.editor.code-editor/snippet.js, line 326 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqh_vGUezPtVGelqH:-K8aqh_wjfLz25P2L12V:-795354786) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/snippet.js#L326)):*
please, remove unused space character

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by gseok** [comment]
*[apps/ide/src/plugins/webida.editor.code-editor/snippet.js, line 555 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqkFxvXBlMrMMs8MO:-K8aqkFy7l-8mXy8oSm3:-795354786) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/snippet.js#L555)):*
please, remove unused space character

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by gseok** [comment]
*[apps/ide/src/plugins/webida.editor.code-editor/snippet.js, line 572 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqlh59eZv6OVHHBcK:-K8aqlh59eZv6OVHHBcL:-795354786) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/snippet.js#L572)):*
please, remove unused space character

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by gseok** [comment]
*[apps/ide/src/plugins/webida.editor.code-editor/snippet.js, line 605 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqpwYQ1Fndy7I9P-p:-K8aqpwYQ1Fndy7I9P-q:-795354786) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/snippet.js#L605)):*
please, remove unused space character

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by gseok** [comment]
*[apps/ide/src/plugins/webida.editor.code-editor/unit-test.js, line 4 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8ar3-vy7Pv2FGCLMY2:-K8ar3-wqPOMI7z_hTKH:-795354786) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/unit-test.js#L4)):*
please, remove unused space character

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by gseok** [comment]
Reviewed 1 of 27 files at r1.
Review status: 1 of 24 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by gseok** [comment]
Reviewed 26 of 27 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by hwshim** [comment]
*[apps/ide/src/plugins/webida.editor.code-editor/unit-test.js, line 4 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8ar3-vy7Pv2FGCLMY2:-K8ciEr_A1n7MaC4mmwz:1487663239) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/unit-test.js#L4)):*
Yep, this can be merged after removing unused white space chars.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by hwshim** [comment]
Reviewed 27 of 27 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by hyukmin-kwon** [comment]
*[apps/ide/src/plugins/webida.editor.code-editor/unit-test.js, line 4 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8ar3-vy7Pv2FGCLMY2:-K8dAmg-9kUtvyaaNSQy:1706342915) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/unit-test.js#L4)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by hyukmin-kwon** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[apps/ide/src/plugins/webida.editor.code-editor/preferences/preference-contentassist.js, line 39 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aq8oWi6xsccBLL1nX:-K8dBYFEqg3E37YWETKW:-499146009) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/preferences/preference-contentassist.js#L39)):*
Done.

---

*[apps/ide/src/plugins/webida.editor.code-editor/preferences/preference-contentassist.js, line 51 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqHhBdJPsJyH3fWn9:-K8dBZ4Vs4xi3Gg_xr6i:-499146009) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/preferences/preference-contentassist.js#L51)):*
Done.

---

*[apps/ide/src/plugins/webida.editor.code-editor/preferences/preference-main.js, line 36 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqM9DLLj8UcRhKFtb:-K8dBZmW8vAFRuaIbW02:-499146009) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/preferences/preference-main.js#L36)):*
Done.

---

*[apps/ide/src/plugins/webida.editor.code-editor/snippet.js, line 322 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqfeRZH2sb6EemTQq:-K8dB_OCpQj2lcZMwpBY:-499146009) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/snippet.js#L322)):*
Done.

---

*[apps/ide/src/plugins/webida.editor.code-editor/snippet.js, line 326 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqh_vGUezPtVGelqH:-K8dB_sSdg8yoFmZbpSJ:-499146009) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/snippet.js#L326)):*
Done.

---

*[apps/ide/src/plugins/webida.editor.code-editor/snippet.js, line 555 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqkFxvXBlMrMMs8MO:-K8dBb1Nt8BAl6SzmcB7:-499146009) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/snippet.js#L555)):*
Done.

---

*[apps/ide/src/plugins/webida.editor.code-editor/snippet.js, line 572 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqlh59eZv6OVHHBcK:-K8dBeHzORKrxQDfXA3O:-499146009) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/snippet.js#L572)):*
Done.

---

*[apps/ide/src/plugins/webida.editor.code-editor/snippet.js, line 605 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8aqpwYQ1Fndy7I9P-p:-K8dBfJnuuqsbRilzRmT:-499146009) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/snippet.js#L605)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by gseok** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Comment by hyukmin-kwon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[apps/ide/src/plugins/webida.editor.code-editor/unit-test.js, line 4 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/883#-K8ar3-vy7Pv2FGCLMY2:-K8dBUnhoDnW1iegdxWQ:-499146009) ([raw file](https://github.com/webida/webida-client/blob/af27759c698693a19ee3612674c2f9715d985872/apps/ide/src/plugins/webida.editor.code-editor/unit-test.js#L4)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/883)*

**Pull request merged**
