### PR TITLE
[FEATURE] (#574) Support IE

### PR DESCRIPTION
**Pull request by kyungmi**
[DESC.]
- Upgrade require.js version for assist-worker (In web worker, require.js might work wrong.)
- Rewrite `Promise` usages in assist-worker.js in ES5

### CODE REVIEW

**Comment by kyungmi** [comment]
I think it is fine to merge this PR, though jshint checking was failed.

**Comment by wcho** [comment]
Why don't you just use nice Promise implementation such as bluebird.js?

**Comment by kyungmi** [comment]
@wcho I looked for and choose the one that can cover almost all of ES6 features. I want to know why you think Bluebird's Promise implementation is better than other.

**Comment by wcho** [comment]
Official promise spec defines very limited APIs to handle promises. For this complex project, you will eventually need something more that implements various helper functions such as filter, reduce, some, map, promisify, etc. It says it's fast and spec compatible plus easy to debug. We are using bluebird internally and satisfied.

**Comment by kyungmi** [comment]
@wcho Thank you for explanation. I'll remind you after setting up the internal decision.

**Pull request merged**
