### PR TITLE
[BUGFIX](#716)Context menu bug on dialog's text input with keyboard's

### PR DESCRIPTION
**Pull request by minsung-jin**
Context menu bug on dialog's text input with keyboard's popup key

  - block key event

Signed-off-by: Minsung Jin <minsung.jin@samsung.com>

[Review on Reviewable](https://reviewable.io/reviews/webida/webida-client/882)

### CODE REVIEW

**Comment by gseok** [comment]
*[common/src/webida/plugins/workbench/command-system/context-menu.js, line 61 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/882#-K8WutHZQTtLsT2r15Ve:-K8WutHZQTtLsT2r15Vf:-23263509) ([raw file](https://github.com/webida/webida-client/blob/2772e6d1374a4a75f8f1b9b2be05abe77eaa235f/common/src/webida/plugins/workbench/command-system/context-menu.js#L61)):*
1. 
built <-- refactoring point...
current code have 'var contextMenu' (contextMenu object).
so... 'contextMenu object could have a own state property'.

<pre>
e.g.)
var contextMenu = new Menu({
   ...
   builtState: false,
   ...
   onBlur: function () {
      this.builtState = false;
   }
});

...

on(document.get....., 'keydown', function (evt) {
   if (!contextMenu.builtState) {
      ...
   }
});
</pre>

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/882)*

**Comment by gseok** [comment]
*[common/src/webida/plugins/workbench/command-system/context-menu.js, line 60 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/882#-K8Wx7b0wWgIcZqW6uQz:-K8Wx7b18933WUUxfoZe:-73347810) ([raw file](https://github.com/webida/webida-client/blob/2772e6d1374a4a75f8f1b9b2be05abe77eaa235f/common/src/webida/plugins/workbench/command-system/context-menu.js#L60)):*
2.  'document.getElementByTagName' function is mulple called (same tag name).
 These code have a 'performance issue'.
 so, my suggestion...
<pre>
   var bodyElement = document.getElementsByTageName('body')[0];
   ...
   bodyElement.addEventListener(....)
   on(bodyElement, ...)
   
</pre>

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/882)*

**Comment by gseok** [comment]
*[common/src/webida/plugins/workbench/command-system/context-menu.js, line 62 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/882#-K8WxCY_1HLRstq4OiFp:-K8WxCY_1HLRstq4OiFq:106639247) ([raw file](https://github.com/webida/webida-client/blob/2772e6d1374a4a75f8f1b9b2be05abe77eaa235f/common/src/webida/plugins/workbench/command-system/context-menu.js#L62)):*
3. add 'commnet' in this logic

e.g)
<pre>
       /*
        * preventDefault and stopPropagation is fixed the
        * Context menu bug on dialog's text input with keyboard's popup key
        * if not prevent .... context menu's key event not woring...
        * if not stpPropagation ... blblblblbblbl
        */
</pre>

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/882)*

**Comment by gseok** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/882)*

**Comment by minsung-jin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/src/webida/plugins/workbench/command-system/context-menu.js, line 60 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/882#-K8Wx7b0wWgIcZqW6uQz:-K8XUwjA8c2sOnwIBLcG:-1392009796) ([raw file](https://github.com/webida/webida-client/blob/2772e6d1374a4a75f8f1b9b2be05abe77eaa235f/common/src/webida/plugins/workbench/command-system/context-menu.js#L60)):*
i applied. thanks for a review.

---

*[common/src/webida/plugins/workbench/command-system/context-menu.js, line 61 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/882#-K8WutHZQTtLsT2r15Ve:-K8XVLetlqGb3_Olob18:-1392009796) ([raw file](https://github.com/webida/webida-client/blob/2772e6d1374a4a75f8f1b9b2be05abe77eaa235f/common/src/webida/plugins/workbench/command-system/context-menu.js#L61)):*
i applied. thanks for a review.

---

*[common/src/webida/plugins/workbench/command-system/context-menu.js, line 62 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/882#-K8WxCY_1HLRstq4OiFp:-K8XVMhAwa3IZIlXHHks:-1392009796) ([raw file](https://github.com/webida/webida-client/blob/2772e6d1374a4a75f8f1b9b2be05abe77eaa235f/common/src/webida/plugins/workbench/command-system/context-menu.js#L62)):*
i applied. thanks for a review.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/882)*

**Comment by gseok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/882)*

**Comment by gseok** [comment]
Nice~!!! :+1:

**Comment by gotchazipc** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[common/src/webida/plugins/workbench/command-system/context-menu.js, line 50 \[r2\]](https://reviewable.io:443/reviews/webida/webida-client/882#-K8YYME_DiUlHxvtf2hi:-K8YYMEaRW2Lg7YM_keL:-2056770444) ([raw file](https://github.com/webida/webida-client/blob/8de18edc222aaf3759b86295f5fac72a33bf9e42/common/src/webida/plugins/workbench/command-system/context-menu.js#L50)):*
do we need contextEvent object? isn't it better move stop function to contextMenu?  

---

*[common/src/webida/plugins/workbench/command-system/context-menu.js, line 57 \[r2\]](https://reviewable.io:443/reviews/webida/webida-client/882#-K8YZfSWIOdH9DsDiEYr:-K8YZfSWIOdH9DsDiEYs:-85073250) ([raw file](https://github.com/webida/webida-client/blob/8de18edc222aaf3759b86295f5fac72a33bf9e42/common/src/webida/plugins/workbench/command-system/context-menu.js#L57)):*
code duplicated to window event listener

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/882)*

**Comment by minsung-jin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/src/webida/plugins/workbench/command-system/context-menu.js, line 60 \[r1\]](https://reviewable.io:443/reviews/webida/webida-client/882#-K8Wx7b0wWgIcZqW6uQz:-K8X_jo_3Ec-_PI2AzEp:-499146009) ([raw file](https://github.com/webida/webida-client/blob/2772e6d1374a4a75f8f1b9b2be05abe77eaa235f/common/src/webida/plugins/workbench/command-system/context-menu.js#L60)):*
Done.

---

*[common/src/webida/plugins/workbench/command-system/context-menu.js, line 50 \[r2\]](https://reviewable.io:443/reviews/webida/webida-client/882#-K8YYME_DiUlHxvtf2hi:-K8YjdwLr2SWpNEV3Qgw:-1392009796) ([raw file](https://github.com/webida/webida-client/blob/8de18edc222aaf3759b86295f5fac72a33bf9e42/common/src/webida/plugins/workbench/command-system/context-menu.js#L50)):*
i applied. thanks for a review.

---

*[common/src/webida/plugins/workbench/command-system/context-menu.js, line 57 \[r2\]](https://reviewable.io:443/reviews/webida/webida-client/882#-K8YZfSWIOdH9DsDiEYr:-K8YjibxhP_5BMNrlwJk:-1392009796) ([raw file](https://github.com/webida/webida-client/blob/8de18edc222aaf3759b86295f5fac72a33bf9e42/common/src/webida/plugins/workbench/command-system/context-menu.js#L57)):*
i applied. thanks for a review.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/882)*

**Comment by gseok** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/882)*

**Comment by minsung-jin** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webida/webida-client/882)*

**Pull request merged**
